### ISSUE TITLE
Hilfslinien / Führungslinien: inconsistent use

### ISSUE THREAD

**Issue by Moini** [Ede123/inkscape-localization#1]
Sollten wir uns hier auf eins von beidem festlegen? (Welches...?)
Google hat mehr Hits für Hilfslinien (235000 vs. 36000), Photoshop und Gimp nennen es auch so. Wikipedia kennt nur diese.

MS Office verwendet Führungslinien.

Schade eigentlich, ich mag 'Führungslinien' ganz gern ;)

**Comment by Ede123** [comment]
Wo sind überhaupt noch "Führungslinien" zu finden? Genau diese Vereinheitlichung habe ich schon vor einiger Zeit zu Gunsten der "Hilfslinie" vorgenommen. Habe ich etwas übersehen?

**Comment by Moini** [comment]
Öhm... _Ich glaub, ich hab mich auf dem Weg zu Demenztestung verlaufen... Wo soll ich nochmal hin?..._ (bloß schnell auf 'Close' klicken...)
