### ISSUE TITLE
Use original name 'Powerstroke' instead of 'Kräftige Kontur'

### ISSUE THREAD

**Issue by su-v** [Ede123/inkscape-localization#3]
Please ... ;-)

(Powerstroke is referring to powerful wrt features for drawing objects with a variable stroke width along the path, not to a large stroke width - eine 'kräftige Kontur' vermittelt mMn nicht die speziellen Eigenschaften dieses Pfadeffekts. Sonst vielleicht eher etwas wie 'Countour dynamique' (Fr), oder 'Contorno evoluto' (It)?)

**Comment by Ede123** [comment]
Not an easy one... Three options I could come up with:
- "Mächtiges Konturwerkzeug"
- "Vielseitige Kontur"
- "Dynamische Kontur"

Does one of these sound reasonable?

(P.S. What's "wrt" supposed to mean in the context above?)

**Comment by su-v** [comment]
@Ede123 
wrt ... with regard to

**Comment by su-v** [comment]
@Moini - was meinst Du?

**Comment by Moini** [comment]
suv versteht uns auch auf Deutsch :) 

Ich hätte das, ehrlich gesagt, auch auf 'Powerstroke' belassen... Ist zwar nicht ge-trademark-ed, wie LPE, aber irgendwie eine spezifische Besonderheit von Inkscape. Das, was am ehesten noch geht ist 'dynamische Kontur' - aber irgendwie klingt das etwas lahm in meinen Ohren. 
Die aktuelle 'Kräftige Kontur' finde ich sehr unpassend. Power-Kontur ist auch doof, oder?

**Comment by Ede123** [comment]
> suv versteht uns auch auf Deutsch :) 

Macht der Gewohnheit. ;-)
Aber ihr habt schon Recht, hier wird wohl sowieso niemand mitreden wollen, der kein Deutsch kann.

Vorschlag: Wenn ihr der Meinung seid, dass "Powerstroke" als Eigenname stehen bleiben bzw. etabliert werden sollte, dann machen wir das doch am besten direkt im Inkscape Code und entfernen die Möglichkeit zur Übersetzung? Dann ist es international einheitlich!
Üblicherweise gehe ich nämlich davon aus, dass jeder String der übersetzt werden _kann_ auch übersetzt werden _soll_ und ich denke mal die meisten anderen Übersetzer machen das genauso... Im Falle des "Powerstroke" wird das generell schwierig sein.

@su-v Du hast meines Wissens Schreibrechte auf das repository? Dann könnte man das ja evtl. als Bugreport / in der Mailingliste kurz ankündigen und dann umsetzen wenn es keine Einwände gibt.

**Comment by Moini** [comment]
Wie Krzysztof sagt (und damit wohl nicht unrecht hat), ist das vielleicht auch abhängig von der Sprachkultur des jeweiligen Landes/Sprachgebiets... 

Ich zum Beispiel käme nie auf die Idee, den Slogan 'Draw freely' zu übersetzen - versteht eh fast jeder, ist getrademarkt, und im Deutschen werden eh ständig Werbebotschaften auf Englisch abgesetzt. So ähnlich geht es mir auch mit dem Powerstroke. Krzysztof würde dagegen zumindest den Slogan wohl ins Polnische übersetzen. Bin mir nicht sicher, ob eine solch generelle Lösung akzeptiert würde... Sonst bleiben wir einfach beim kgN - dynamische Kontur ;)

**Comment by su-v** [comment]
On 2015-10-24 18:25 (+0100), Eduard Braun wrote:

> Vorschlag: Wenn ihr der Meinung seid, dass "Powerstroke" als
> Eigenname stehen bleiben bzw. etabliert werden sollte, dann machen
> wir das doch am besten direkt im Inkscape Code und entfernen die
> Möglichkeit zur Übersetzung? Dann ist es international einheitlich!

Ich weiss nicht genau, wie leicht so ein Vorschlag technisch zu implementieren ist - 'Powerstroke' wird ja auch innerhalb von längeren _strings_ verwendet. Gibt es da ein spezielles _gettext feature_, mit dem man 'Eigennamen' innerhalb eines _strings_ auszeichnen kann?

Mein Vorschlag wäre, das z.B. auf der inkscape-translator Mailingliste zu diskutieren: wie wird es in anderen Übersetzungen gehandhabt, gibt es übereinstimmend den Wunsch, dass das global festgelegt wird und nicht in der Kompetenz des einzelnen Übersetzers liegt, etc.

Persönlich würde ich in der dt. Übersetzung den Eigennamen 'Powerstroke' vorziehen, ansonsten - falls Übersetzung erwünscht ist - vielleicht 'Variable Kontur' (allenfalls auch 'Dynamische Kontur', obwohl für mich im dt. Sprachgebrauch 'dynamisch' zu sehr Eigenschaften wie 'animiert' oder Veränderungen (z.B. basierend auf Faktoren wie 'Dauer') ohne Benutzerinteraktion assoziiert).

**Comment by Ede123** [comment]
OK, wenn wir drei uns schon nicht einig sind, dann macht es wohl keinen Sinn deswegen ein Fass aufzumachen. Dann lassen wir die Übersetzungsmöglichkeit so wie sie ist und es jedes Übersetzungsteam kann selbst entscheiden.

Wir können dann wie von euch gewünscht den "Powerstroke" unübersetzt verwenden, allerdings würde ich noch den Klammerzusatz "(variable Konturbreite)" vorschlagen, denn unter "Powerstroke" alleine kann sich mit Sicherheit niemand etwas vorstellen, der den Effekt nicht bereits kennt.

**Comment by Moini** [comment]
(sogar 'Inkscape' ist übersetzbar... :) - hab ich gestern erst gesehen, als jemand danach gefragt hat, wie man denn den Namen austauschen kann...) 

Ich finde Deinen Vorschlag gut, Eduard - ist auch nicht zu lang und sollte damit im Pfadeffekte-Dialog gut reinpassen, ich wär' damit rundum zufrieden :)

@su-v : Was sagst Du?

**Comment by su-v** [comment]
On 2015-10-27 18:18 (+0100), Eduard Braun wrote:

> Wir können dann wie von euch gewünscht den "Powerstroke" unübersetzt verwenden, allerdings würde ich noch den Klammerzusatz "(variable Konturbreite)" vorschlagen, denn unter "Powerstroke" alleine kann sich mit Sicherheit niemand etwas vorstellen, der den Effekt nicht bereits kennt.

Bei soviel Unbehagen zur Verwendung von _Powerstroke_ als Eigennamen mag ich dem vorgeschlagenen Kompromiss nicht wirklich zustimmen. Ich überlasse es dem aktiven Übersetzerteam, sich zu einigen ;-)

Die vorgeschlagene zusätzliche Erläuterung im Klammersatz wäre idealerweise in einem _tooltip_ (aber den kann man ja nicht via Übersetzung einfach so hinzufügen).

**Comment by Ede123** [comment]
Warum einigen? Das "aktive Übersetzerteam" war sich doch bereits einig? Nur deine Stimme hat noch gefehlt. ;-)

Mit obigem Commit solle es jetzt erstmal erledigt sein. Tooltips wären sicher schön, fraglich nur ob sich jemand auftreiben lässt der die nötigen Änderungen am Code durchführt?
