### ISSUE TITLE
Maske / Maskierung: unify translation

### ISSUE THREAD

**Issue by Moini** [Ede123/inkscape-localization#4]
Welches von beidem sollen wir nehmen?

Maske hat zwar noch viele weitere Bedeutungen, scheint aber (zumindest was Gimp und PS angeht) das gebräuchlichere zu sein, weshalb ich die eher nehmen würde.

Was denkst Du, @Ede123 ?

**Comment by Ede123** [comment]
Rein sprachlich sind "Maske" uns "Maskierung" zwei unterschiedliche Dinge also nicht austauschbar:
- Die Maske bezeichnet das Objekt mit dem maskiert wird (in Inkscape wäre das dann ein Pfad).
- Maskierung ist der Vorgang des Maskierens an sich (d.h. das Setzen der Maske resultiert in einer Maskierung des Ausgangsobjekts).

Im konkreten Fall ist die Übersetzung aber schlicht falsch: Das Substantiv "mask" ist im Deutschen die "Maske" (und nicht die "Maskierung", die wäre nämlich "masking"), weswegen wir bedenkenlos austauschen können.

**Comment by Moini** [comment]
Gut - dann schau ich mal durch - bitte korrigiere oder kommentiere, wo ich's falsch mache :)

Was machst Du, wenn Du die Wahl hast zw. 'Maskierung aufheben' und 'Maske aufheben'? (ähnlich: Maske setzen, Maskierung setzen - Du schreibst oben 'Maske setzen')

Im Englischen Original steht 'Maske aufheben/setzen' - aber rein technisch bleibt die Maske drin, nur die Tatsache, dass sie maskierend wirkt, wird aufgehoben... 

Der Unterschied masking / mask wird also dann schon im Englischen nicht konsequent eingehalten, oder hab ich das jetzt ganz verquer verstanden?

**Comment by Moini** [comment]
Okay so? 
https://github.com/Ede123/inkscape-localization/commit/17f8027aec6cfbe7212c57ce29b93f9741f1f5a6

**Comment by Ede123** [comment]
> Was machst Du, wenn Du die Wahl hast zw. 'Maskierung aufheben' und 'Maske aufheben'?
> "Maske aufheben" macht tatsächlich wenig Sinn (sie liegt ja nicht auf dem Boden ;-) )

Wenn Maske, dann legt man einen Pfad als Maske fest bzw. "setzt" diesen Pfad als Maske (zweiteres ist schon etwas denglisch denke ich).
Antonym zu festlegen wird hingegen tatsächlich schwierig. "Lösen" vielleicht? Oder einfach "entfernen"?

Maskierung aufheben geht, klingt aber auch irgendwie merkwürdig. Ich glaube das richtige wor wre "Demaskieren", aber im Kontext wäre das doch seeehr undeutlich.

**Comment by Moini** [comment]
:)

Aktuell sind die Übersetzungen dafür: 
Maskierung (Ausschneidepfad) entfernen, Maskierung (Ausschneidepfad) setzen.
Die beiden überlasse ich lieber Dir, vielleicht findest Du ja noch was Geeigneteres.

Demaskieren klingt für mich auch eher nach Agenten-Thriller ;) (und im medizinischen Kontext kommt das häufiger mal vor).

**Comment by Moini** [comment]
(Masken können übrigens auch aus Gruppen bestehen - nur falls Dir jetzt 'Maskenpfad' einfällt)

**Comment by Ede123** [comment]
Habe gerade nochmal ein paar Änderungen vorgenommen. Haben wir jetzt alles erwischt?

**Comment by Moini** [comment]
Sieht so aus :) Ich hoffe, meine Kommentare bringen Dich nicht zur Verzweiflung - falls ja, ignorier sie einfach.

**Comment by Ede123** [comment]
Nein überhaupt nicht, die drehen sich nämlich fast alle um das selbe Problem: #5 

Dort hatte ich bereits ein paar mögliche Lösungsansätze angesprochen.

P.S. Sorry, hier hätte ich wohl direkt einen Hinweis auf das neue Problem irgendwo platzieren sollen.
