### ISSUE TITLE
Translation for clip path / clip

### ISSUE THREAD

**Issue by Ede123** [Ede123/inkscape-localization#5]
Bin gerade am Grübeln was hier die passendste Übersetzung wäre.

Derzeit verwenden wir fast überall "clip path" -> "Ausschneidepfad"
Das funktioniert zwar, ist aber nur die halbe Wahrheit, da das Objekt nicht zwangsweise ein (einzelner) Pfad ist.

Deshalb bräuchten wir eine Übersetzung für einen allgemeinen "Clip", d.h. ein allgemeines Objekt welches zum Beschneiden benutzt wird. Derzeit wird aus "clip" wird dann oft "Ausschneidung" (klingt meiner Meinung nach fürchterlich, trifft die Bedeutung nicht richtig und ist eher unklar).

Was wäre denn die beste Übersetzung für "clip"?
Ausschnitt? (ebenfalls unklar)
Schnittmuster? (nicht viel besser)
Photoshop kennt eine "Schnittmaske" ("clipping mask"). (Potentielle Verwechslungsgefahr mit einer einfachen "Maske", auf der anderen Seite handelt es sich auch um ähnliche Werkzeuge und diese Analogie könnte damit sogar positiv sein)

Habt ihr Ideen?

**Comment by Moini** [comment]
Ah, okay, das erklärt den Ausschnitt im commit. 
Ich empfinde 'Ausschnitt' analog zu 'Maskierung'.... eher der Vorgang als das Objekt.

/brainstorm mode on/
Schnittobjekt
Beschnittobjekt
Ausschneideobjekt
Ausschneidemaske
(trimmen, stutzen,...)
/brainstorm mode off/

**Comment by Ede123** [comment]
Nö, das bezieht sich nur auf das referenzierte issue.

**Comment by Moini** [comment]
(habe ich dann auch begriffen... Sch... ajax und zu spät am Abend... ;))

**Comment by Ede123** [comment]
Desto mehr ich darüber nachdenke desto besser gefällt mir die "Ausschneidemaske".

Wenn wir "Ausschneidemaske" für "clip" verwenden, dann können wir den "Ausschneidepfad" parallel als "clip path" weiterverwenden.
Längerfristig scheint der "clip path" dann ohnehin zugunsten des "clip" ausgemustert zu werden, und so schaffen wir den Übergang fließend.
