### ISSUE TITLE
"Canvas" - "Leinwand" oder "Zeichenfläche"?

### ISSUE THREAD

**Issue by Ede123** [Ede123/inkscape-localization#6]
Wir haben derzeit beides. Sollte eine Übersetzung bevorzugt werden?

**Comment by Moini** [comment]
Ich bin für 'Zeichenfläche' - was ist Dein Favorit, Eduard?

**Comment by Ede123** [comment]
Ich bin unentschieden, da
- Leinwand konsistent in GIMP verwendet wird und deshalb eine projektübergreifende Konsistenz hergestellt werden könnte. Allerdings ist in GIMP die "Leinwand" eher das, was bei uns die "Seite" ist.
- Zeichenfläche meiner Meinung nach unmittelbarer beschreibt um was es geht und deshalb tendenziell die bessere Übersetzung wäre.
- Gerade noch eine dritte Option entdeckt: "Arbeitsfläche"

Ich tendiere tatsächlich zur Option drei, da sie genauso klar ist wie "Zeichenfläche" aber nicht Gefahr läuft mit der "Fläche der Zeichnung" verwechselt zu werden, die ja tendenziell nur einen Bruchteil der "Arbeitsfläche" beträgt.

**Comment by Moini** [comment]
Zur Leinwand dachte ich genau dasselbe ;)

Arbeitsfläche ist auch gut, Deine Begründung leuchtet mir ein.
