### ISSUE TITLE
entsperret -> entsperrt

### ISSUE THREAD

**Issue by Moini** [Ede123/inkscape-localization#7]
Hallo Eduard,
da unsere po-Datei zu groß für's Online-Editieren ist und ich noch für ein paar Tage keinen eigenen PC haben werde, wollte ich fragen, ob Du die Ersetzung aus dem Titel dieses Fehlerberichts vielleicht vornehmen könntest (in der trunk-po-Datei). Fiel mir auf, als ich ins Diff bei launchpad geschaut habe (denke mal, ich hab da versehentlich wohl ein bisschen zu wenig ersetzt...)

**Comment by Ede123** [comment]
Sorry, aber ich bin seit gestern auf Reisen und habe die nächsten drei 
Wochen ebenfalls keinen PC zur Hand.

Muss also wohl warten...

Am 15. Juli 2016 3:52:00 vorm. schrieb Moini notifications@github.com:

**Comment by Moini** [comment]
Okay, danke für die Antwort und gute Reise!
