### ISSUE TITLE
0.91 directory: can it be removed?

### ISSUE THREAD

**Issue by Moini** [Ede123/inkscape-localization#8]
Moin Eduard,
brauchen wir das Verzeichnis für 0.91 eigentlich noch?

**Comment by Ede123** [comment]
Nö... stören tut's aber auch nicht, oder?

**Comment by Ede123** [comment]
Im "board meeting" ging's übrigens grad um 0.91.2 :-D
(eher aber als Missverständnis auf Grund eines Schreibfehlers)

**Comment by Moini** [comment]
Ach ja, das... Verpasst. Vielleicht besser so.

**Comment by Moini** [comment]
Nö, stört nicht. Wurde der 0.91.x Zweig jetzt eigentlich endlich offiziell eingestampft?

**Comment by Ede123** [comment]
Nein, offiziell wird das glaube ich auch nichts mehr...
Fand's umso lustiger, dass Bryce ernsthaft 0.91.2 in Erwägung gezogen hatte. Vielleicht haben wir das 0.91.1 Release auch nur verpasst? 🤐

**Comment by Moini** [comment]
Okay, dann mach ich den hier zu :)
